baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Charcaterisation eResearch & Data Science'
theme = "hugo-theme-techdoc"

[menu]
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[params]
menu_style = "open-menu" # "open-menu" or "slide-menu" or "" blank is as no sidebar

[outputs]
    home = ["HTML", "RSS", "Algolia"]

# Algolia Search configure section
[outputFormats.Algolia]
    baseName = "algolia"
    mediaType = "application/json"
    isPlainText = true
    notAlternative = true

[params.algolia]
    vars = [
        "title",
        "summary",
        "content",
        "date",
        "publishdate",
        "description",
        "permalink",
        "keywords",
        "lastmod",
    ]
    params = [
        "tags",
        "categories",
    ]
